knpu_oauth2_client:
    clients:
        google:
            # Обязательно: измените client_id и client_secret на реальные данные вашего Google API проекта
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            type: 'google'
            redirect_route: 'google.connect_check'
            redirect_params: {}
