security:
    enable_authenticator_manager: true

    providers:
        google_provider:
            id: user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            entry_point: security.auth.entry_point
            logout:
                path: /logout
                target: / #This is home url
            provider: google_provider
            custom_authenticators:
                - google_authenticator

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }