name: "Deploy"
description: 'Deploys the application to the server'
inputs:
  ssh_password:
    description: 'SSH password for the remote server'
    required: true
  php_container:
    description: 'PHP container name'
    required: false
    default: 'muzone_php'
  folder:
    description: 'Folder for deployment'
    required: false
    default: '/root/www/muzone/deployment/'
  project_folder:
    description: 'Folder for deployment'
    required: false
    default: '/root/www/muzone/'
  container_folder:
    description: 'Folder for deployment'
    required: false
    default: '/srv/src/muzone/html/'
  timestamp:
    description: 'Timestamp for deployment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Debug information
      run: |
        echo "Environment Variables:"
        env
        echo "---------------------------------------"
        echo "Current Directory:"
        pwd
        echo "---------------------------------------"
        echo "Directory Content:"
        ls -la
        echo "SSH Password: ${{ inputs.ssh_password }}"
      shell: bash

    - name: Deploy to server with rsync
      run: |
        sshpass -p '${{ inputs.ssh_password }}' rsync -avz -e 'ssh -o StrictHostKeyChecking=no' --exclude '.git' --exclude 'var' . root@185.215.180.50:${{ inputs.folder }}${{ inputs.timestamp }}
      shell: bash

    - name: SSH to server and run commands
      run: |
        sshpass -p ${{ inputs.ssh_password }} ssh root@185.215.180.50 <<'ENDSSH'
          sops --decrypt ${{ inputs.folder }}${{ inputs.timestamp }}/.env.local.sops > ${{ inputs.folder }}${{ inputs.timestamp }}/.env.local
          ln -sfn ${{ inputs.folder }}${{ inputs.timestamp }} ${{ inputs.project_folder }}current
        ENDSSH
      shell: bash
