main_page:
    path: /
    controller: Infrastructure\Symfony\Controller\MainPageController

contact.save:
    path: /contact
    controller: Infrastructure\Symfony\Controller\LeadController::save
    methods: [ POST ]
