main_page:
    path: /
    controller: Infrastructure\Symfony\Controller\MainPageController

contact_save:
    path: /contact/save
    controller: Infrastructure\Symfony\Controller\ContactController::save
    methods: [ POST ]
