parameters:

services:
  Infrastructure\Symfony\Controller\MainPageController:
    public: true
    tags: ['controller.service_arguments', 'container.service_subscriber']
    calls:
      - [setContainer, ['']]

  infrastructure.images:
    class: Infrastructure\Twig\GlobalVariables

  Infrastructure\Symfony\ArgumentResolver\SaveContactCommandArgumentResolver:
    tags: [ 'controller.argument_value_resolver' ]

  contact_repository.psql:
    class: Infrastructure\Persistence\Psql\Repository\ContactRepository
    arguments:
      - '@database_connection'

  contact_repository:
    alias: contact_repository.psql

  contact_save_handler:
    class: Application\Contact\SaveContactHandler
    arguments:
      - '@contact_repository'