parameters:

services:
  Infrastructure\Symfony\Controller\MainPageController:
    public: true
    tags: ['controller.service_arguments', 'container.service_subscriber']
    calls:
      - [setContainer, ['']]

  Infrastructure\Symfony\ArgumentResolver\SaveLeadCommandArgumentResolver:
    tags: [ 'controller.argument_value_resolver' ]

  Infrastructure\Symfony\Controller\LeadController:
    public: true
    tags: ['controller.service_arguments', 'container.service_subscriber']
    calls:
      - [setContainer, ['']]
    arguments:
      - '@lead.handler_save'

  infrastructure.images:
    class: Infrastructure\Twig\GlobalVariables

  lead_repository.psql:
    class: Infrastructure\Persistence\Psql\Repository\LeadRepository
    arguments:
      - '@database_connection'
      - '@uuid.factory'

  lead_repository:
    alias: lead_repository.psql

  lead.contact_factory:
    class: Domain\Lead\Contact\ContactFactory

  lead.handler_save:
    class: Application\Lead\SaveLeadHandler
    arguments:
      - '@lead_repository'
      - '@lead.contact_factory'