name: Build and test

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/genkovich/muzone_php82
      options: --workdir /srv/src/muzone/html

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          echo "Current Directory:"
          pwd

      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: ./vendor/bin/phpunit

      - name: Build Front
        run: | 
          yarn install && yarn run build
          echo "Current Directory:"
          pwd

      - name: Set timestamp
        id: set_timestamp
        run: |
          echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

      - uses: ./.github/actions/deploy
        id: deploy
        with:
          ssh_password: ${{ secrets.SSH_PASSWORD }}
          timestamp: ${{ steps.set_timestamp.outputs.timestamp }}